// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.solution4future.models;

import com.solution4future.models.CustomerAction;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomerAction_Roo_Configurable {
    
    declare @type: CustomerAction: @Configurable;
    
}
